<a href="https://colab.research.google.com/github/Kaleab1999/text-analytics-NLP/blob/main/Stock_market_sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df=pd.read_csv('/content/drive/MyDrive/dataset/stock sentiment.csv')
df.head()

Date  Label                                               Top1  \
0  2000-01-03      0  A 'hindrance to operations': extracts from the...   
1  2000-01-04      0                                          Scorecard   
2  2000-01-05      0                  Coventry caught on counter by Flo   
3  2000-01-06      1                      Pilgrim knows how to progress   
4  2000-01-07      1                               Hitches and Horlocks   

                                 Top2  \
0                           Scorecard   
1                 The best lake scene   
2  United's rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                            Top3  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                            Top4  \
0       Jack gets his skates on at ice-cold Alex   
1                                  Cheerio, boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                          Top5  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   

                                                Top6  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   

                                              Top7  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees?   
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                Top8  ...  \
0                  Gunners so wide of an easy target  ...   
1                             Has Cubie killed fees?  ...   
2               Cullinan continues his Cape monopoly  ...   
3  Hussain hurt by 'shambles' but lays blame on e...  ...   
4                   Whingers - a formidable minority  ...   

                                               Top16  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne (Australia)   
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere:  UDIs   

                                               Top17  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa (Mexico)   
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted:  Chloe lunettes   

                                            Top18  \
0             Kohl's successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid (Spain)   
3                     How much can you pay for...   
4  Return of the cane 'completely off the agenda'   

                                               Top19  \
0               The difference between men and women   
1  Irish court halts IRA man's extradition to Nor...   
2                          Raja Casablanca (Morocco)   
3                                 Christmas glitches   
4                   From Sleepy Hollow to Greeneland   

                         

In [4]:
train = df[df['Date'] < '20150101']
test = df[df['Date'] > '20141231']

In [5]:
df.tail()

Date  Label                                               Top1  \
4096  2016-06-27      0  Barclays and RBS shares suspended from trading...   
4097  2016-06-28      1  2,500 Scientists To Australia: If You Want To ...   
4098  2016-06-29      1                   Explosion At Airport In Istanbul   
4099  2016-06-30      1  Jamaica proposes marijuana dispensers for tour...   
4100  2016-07-01      1  A 117-year-old woman in Mexico City finally re...   

                                                   Top2  \
4096  Pope says Church should ask forgiveness from g...   
4097  The personal details of 112,000 French police ...   
4098  Yemeni former president: Terrorism is the offs...   
4099  Stephen Hawking says pollution and 'stupidity'...   
4100   IMF chief backs Athens as permanent Olympic host   

                                                   Top3  \
4096  Poland 'shocked' by xenophobic abuse of Poles ...   
4097  S&amp;P cuts United Kingdom sovereign credit r...   
4098  UK must accept freedom of movement to access E...   
4099  Boris Johnson says he will not run for Tory pa...   
4100  The president of France says if Brexit won, so...   

                                                   Top4  \
4096  There will be no second referendum, cabinet ag...   
4097                Huge helium deposit found in Africa   
4098  Devastated: scientists too late to captive bre...   
4099  Six gay men in Ivory Coast were abused and for...   
4100  British Man Who Must Give Police 24 Hours' Not...   

                                                   Top5  \
4096      Scotland welcome to join EU, Merkel ally says   
4097  CEO of the South African state broadcaster qui...   
4098  British Labor Party leader Jeremy Corbyn loses...   
4099  Switzerland denies citizenship to Muslim immig...   
4100  100+ Nobel laureates urge Greenpeace to stop o...   

                                                   Top6  \
4096  Sterling dips below Friday's 31-year low amid ...   
4097  Brexit cost investors $2 trillion, the worst o...   
4098  A Muslim Shop in the UK Was Just Firebombed Wh...   
4099  Palestinian terrorist stabs israeli teen girl ...   
4100  Brazil: Huge spike in number of police killing...   

                                                   Top7  \
4096  No negative news about South African President...   
4097  Hong Kong democracy activists call for return ...   
4098  Mexican Authorities Sexually Torture Women in ...   
4099  Puerto Rico will default on $1 billion of debt...   
4100  Austria's highest court annuls presidential el...   

                                                   Top8  ...  \
4096  Surge in Hate Crimes in the U.K. Following U.K...  ...   
4097  Brexit: Iceland president says UK can join 'tr...  ...   
4098            UK shares and pound continue to recover  ...   
4099  Republic of Ireland fans to be awarded medal f...  ...   
4100  Facebook wins privacy case, can track any Belg...  ...   

                                                  Top16  \
4096  German lawyers to probe Erdogan over alleged w...   
4097  US, Canada and Mexico pledge 50% of power from...   
4098  Escape Tunnel, Dug by Hand, Is Found at Holoca...   
4099  Googles free wifi at Indian railway stations i...   
4100  The United States has placed Myanmar, Uzbekist...   

                                                  Top17  \
4096  Boris Johnson says the UK will continue to "in...   
4097  There is increasing evidence that Australia is...   
4098  The land under Beijing is sinking by as much a...   
4099  Mounting evidence suggests 'hobbits' were wipe...   
4100  S&amp;P revises European Union credit rating t...   

                                                  Top18  \
4096  Richard Branson is calling on the UK governmen...   
4097  Richard Branson, the founder of Virgin Group, ...   
4098  Car bomb and Anti-Islamic attack on Mosque in ...   
4099  The men who carried out Tuesday's terror attac...   
4100  India gets $1 bil

In [6]:
test.shape,train.shape

((378, 27), (3975, 27))

In [7]:
data=train.iloc[:,2:27]
data2= test.iloc[:,2:27]

In [8]:
list1= [i for i in range(25)]
new_Index=[str(i) for i in list1]
data.columns= new_Index
data.head(5)

0  \
0  A 'hindrance to operations': extracts from the...   
1                                          Scorecard   
2                  Coventry caught on counter by Flo   
3                      Pilgrim knows how to progress   
4                               Hitches and Horlocks   

                                    1  \
0                           Scorecard   
1                 The best lake scene   
2  United's rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                               2  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                               3  \
0       Jack gets his skates on at ice-cold Alex   
1                                  Cheerio, boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                             4  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   

                                                   5  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   

                                                 6  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees?   
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                   7  \
0                  Gunners so wide of an easy target   
1                             Has Cubie killed fees?   
2               Cullinan continues his Cape monopoly   
3  Hussain hurt by 'shambles' but lays blame on e...   
4                   Whingers - a formidable minority   

                                                   8  \
0      Derby raise a glass to Strupar's debut double   
1  Hopkins 'furious' at Foster's lack of Hannibal...   
2             McGrath puts India out of their misery   
3                      England's decade of disasters   
4                             Alan Parker - part two   

                                          9  ...  \
0  Southgate strikes, Leeds pay the penalty  ...   
1                    Has Cubie killed fees?  ...   
2            Blair Witch bandwagon rolls on  ...   
3      Revenge is sweet for jubilant Cronje  ...   
4                 Thuggery, Toxins and Ties  ...   

                                                  15  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne (Australia)   
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere:  UDIs   

                                                  16  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa (Mexico)   
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted:  Chloe lunettes   

                                               17  \
0             Kohl's successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid (Spain)   
3    

In [9]:
list2= [i for i in range(25)]
new_Index2=[str(i) for i in list1]
data2.columns= new_Index
data2.head(5)

0  \
3723  Most cases of cancer are the result of sheer b...   
3724  Moscow-&gt;Beijing high speed train will reduc...   
3725                    US oil falls below $50 a barrel   
3726                'Shots fired' at French magazine HQ   
3727  New Charlie Hebdo issue to come out next week:...   

                                                      1  \
3723  Iran dismissed United States efforts to fight ...   
3724  Two ancient tombs were discovered in Egypt on ...   
3725  Toyota gives away 5,680 fuel cell patents to b...   
3726    90% of Bibi Netanyahus Campaign Funds From U.S.   
3727  Ahmed Merabet, Cop Killed In Paris Attacks, Wa...   

                                                      2  \
3723  Poll: One in 8 Germans would join anti-Muslim ...   
3724  China complains to Pyongyang after N Korean so...   
3725  Young Indian couple who had been granted polic...   
3726  ISIS behead street magician for entertaining c...   
3727  Youngest Suspect in Charlie Hebdo Attack Turns...   

                                                      3  \
3723  UK royal family's Prince Andrew named in US la...   
3724  Scotland Headed Towards Being Fossil Fuel-Free...   
3725  A senior figure in Islamic States self-declare...   
3726  Denmark sets new world record in renewable ene...   
3727  Grenades thrown at a mosque in Le Mans, west o...   

                                                      4  \
3723  Some 40 asylum-seekers refused to leave the bu...   
3724  Prime Minister Shinzo Abe said Monday he will ...   
3725  Fukushima rice passes radiation tests for 1st ...   
3726  ISIS Closes Schools In Syria, Leaving 670000 C...   
3727  Danish newspaper to print Charlie Hebdo cartoo...   

                                                      5  \
3723  Pakistani boat blows self up after India navy ...   
3724  Sex slave at centre of Prince Andrew scandal f...   
3725  Nearly all Spanish parties guilty of financial...   
3726  The European Union wants Turkey to explain how...   
3727  Muslim politician from India offers $8M to Cha...   

                                                      6  \
3723  Sweden hit by third mosque arson attack in a week   
3724  Gay relative of Hamas founder faces deportatio...   
3725             King Abdullah to abdicate Saudi Throne   
3726  10 people have died in a shooting at the headq...   
3727  Vladimir Putin has condemned a deadly terroris...   

                                                      7  \
3723         940 cars set alight during French New Year   
3724  The number of female drug addicts in Iran has ...   
3725    Taliban Commander Caught Networking On LinkedIn   
3726  Most Earth-like planet ever discovered could b...   
3727  Turkey is trying to hide any evidence that hol...   

                                                      8  \
3723  Salaries for top CEOs rose twice as fast as av...   
3724  After Decades of Searching, the Causeway for t...   
3725  Mexican missing students: mayor's wife charged...   
3726  New questions raised about U.S.-Saudi relation...   
3727  Danish Paper That Published 12 Muhammad Cartoo...   

                                                      9  ...  \
3723  Norway violated equal-pay law, judge says: Jud...  ...   
3724                       India lost 64 tigers in 2014  ...   
3725  New York Times reporter James Risen refused on...  ...   
3726  Massive hunt underway for gunmen in Paris terr...  ...   
3727  Two Charlie Hebdo attackers located in north F...  ...   

                                                     15  \
3723  Ukrainian minister threatens TV channel with c...   
3724  The Islamic State has approved a 2015 budget o...   
3725  Thousands of Indians have fled from their home...   
3726  Discovery of witnesss mutilated body feeds cla...   
3727  Thousands in Europe hold up Pens in Solidarity...   

                                                     16  \
3723  Palestinian President Mahmoud Abbas has entere...   
3

In [10]:
# Normalization
for index in new_Index:
    data[index]=data[index].str.lower()

for index in new_Index2:
    data2[index]=data2[index].str.lower()
data.head(1)

0          1  \
0  a 'hindrance to operations': extracts from the...  scorecard   

                                 2                                         3  \
0  hughes' instant hit buoys blues  jack gets his skates on at ice-cold alex   

                                        4  \
0  chaos as maracana builds up for united   

                                                   5  \
0  depleted leicester prevail as elliott spoils e...   

                                  6                                  7  \
0  hungry spurs sense rich pickings  gunners so wide of an easy target   

                                               8  \
0  derby raise a glass to strupar's debut double   

                                          9  ...  \
0  southgate strikes, leeds pay the penalty  ...   

                                         15  \
0  flintoff injury piles on woe for england   

                                                  16  \
0  hunters threaten jospin with new battle of the...   

                                    17                                    18  \
0  kohl's successor drawn into scandal  the difference between men and women   

                                    19  \
0  sara denver, nurse turned solicitor   

                                               20  \
0  diana's landmine crusade put tories in a panic   

                                                  21                22  \
0  yeltsin's resignation caught opposition flat-f...  russian roulette   

         23                  24  
0  sold out  recovering a title  

[1 rows x 25 columns]

In [11]:
data2.head()

0  \
3723  most cases of cancer are the result of sheer b...   
3724  moscow-&gt;beijing high speed train will reduc...   
3725                    us oil falls below $50 a barrel   
3726                'shots fired' at french magazine hq   
3727  new charlie hebdo issue to come out next week:...   

                                                      1  \
3723  iran dismissed united states efforts to fight ...   
3724  two ancient tombs were discovered in egypt on ...   
3725  toyota gives away 5,680 fuel cell patents to b...   
3726    90% of bibi netanyahus campaign funds from u.s.   
3727  ahmed merabet, cop killed in paris attacks, wa...   

                                                      2  \
3723  poll: one in 8 germans would join anti-muslim ...   
3724  china complains to pyongyang after n korean so...   
3725  young indian couple who had been granted polic...   
3726  isis behead street magician for entertaining c...   
3727  youngest suspect in charlie hebdo attack turns...   

                                                      3  \
3723  uk royal family's prince andrew named in us la...   
3724  scotland headed towards being fossil fuel-free...   
3725  a senior figure in islamic states self-declare...   
3726  denmark sets new world record in renewable ene...   
3727  grenades thrown at a mosque in le mans, west o...   

                                                      4  \
3723  some 40 asylum-seekers refused to leave the bu...   
3724  prime minister shinzo abe said monday he will ...   
3725  fukushima rice passes radiation tests for 1st ...   
3726  isis closes schools in syria, leaving 670000 c...   
3727  danish newspaper to print charlie hebdo cartoo...   

                                                      5  \
3723  pakistani boat blows self up after india navy ...   
3724  sex slave at centre of prince andrew scandal f...   
3725  nearly all spanish parties guilty of financial...   
3726  the european union wants turkey to explain how...   
3727  muslim politician from india offers $8m to cha...   

                                                      6  \
3723  sweden hit by third mosque arson attack in a week   
3724  gay relative of hamas founder faces deportatio...   
3725             king abdullah to abdicate saudi throne   
3726  10 people have died in a shooting at the headq...   
3727  vladimir putin has condemned a deadly terroris...   

                                                      7  \
3723         940 cars set alight during french new year   
3724  the number of female drug addicts in iran has ...   
3725    taliban commander caught networking on linkedin   
3726  most earth-like planet ever discovered could b...   
3727  turkey is trying to hide any evidence that hol...   

                                                      8  \
3723  salaries for top ceos rose twice as fast as av...   
3724  after decades of searching, the causeway for t...   
3725  mexican missing students: mayor's wife charged...   
3726  new questions raised about u.s.-saudi relation...   
3727  danish paper that published 12 muhammad cartoo...   

                                                      9  ...  \
3723  norway violated equal-pay law, judge says: jud...  ...   
3724                       india lost 64 tigers in 2014  ...   
3725  new york times reporter james risen refused on...  ...   
3726  massive hunt underway for gunmen in paris terr...  ...   
3727  two charlie hebdo attackers located in north f...  ...   

                                                     15  \
3723  ukrainian minister threatens tv channel with c...   
3724  the islamic state has approved a 2015 budget o...   
3725  thousands of indians have fled from their home...   
3726  discovery of witnesss mutilated body feeds cla...   
3727  thousands in europe hold up pens in solidarity...   

                                                     16  \
3723  palestinian president mahmoud abbas has entere...   
3

In [12]:
headlines = []
for row in range(0,len(data.index)):
    headlines.append(' '.join(str(x) for x in data.iloc[row,0:25]))

test_data = []
for row in range(0,len(data2.index)):
    test_data.append(' '.join(str(x) for x in data2.iloc[row,0:25]))

In [13]:
headlines[0]

"a 'hindrance to operations': extracts from the leaked reports scorecard hughes' instant hit buoys blues jack gets his skates on at ice-cold alex chaos as maracana builds up for united depleted leicester prevail as elliott spoils everton's party hungry spurs sense rich pickings gunners so wide of an easy target derby raise a glass to strupar's debut double southgate strikes, leeds pay the penalty hammers hand robson a youthful lesson saints party like it's 1999 wear wolves have turned into lambs stump mike catches testy gough's taunt langer escapes to hit 167 flintoff injury piles on woe for england hunters threaten jospin with new battle of the somme kohl's successor drawn into scandal the difference between men and women sara denver, nurse turned solicitor diana's landmine crusade put tories in a panic yeltsin's resignation caught opposition flat-footed russian roulette sold out recovering a title"

In [14]:
test_data[1]

'moscow-&gt;beijing high speed train will reduce trip time to 48 hours, from the current 7 days two ancient tombs were discovered in egypt on sunday, with one representing a symbolic burial site of the god osiris while another is claimed to be a previously unknown pharaonic tomb. china complains to pyongyang after n korean soldier kills villagers | world news scotland headed towards being fossil fuel-free by 2030 - renewable energy projects combined with energy savings could decarbonise the countrys power sector. "we need to see the phasing out of conventional generation in scotland." prime minister shinzo abe said monday he will express remorse for japans actions in world war ii while highlighting the countrys bid to contribute more actively to world peace in his statement marking the 70th anniversary of the wars end in august. sex slave at centre of prince andrew scandal fled to australia as a teen gay relative of hamas founder faces deportation from canada: christian convert, 24, wh

In [15]:
data = pd.DataFrame(headlines)
data2= pd.DataFrame(test_data)

data.head()

0
0  a 'hindrance to operations': extracts from the...
1  scorecard the best lake scene leader: german s...
2  coventry caught on counter by flo united's riv...
3  pilgrim knows how to progress thatcher facing ...
4  hitches and horlocks beckham off but united su...

In [16]:
corpus=[]
corpus2=[]
con={
    "ain't": "am not / are not / is not / has not / have not",
"aren't": "are not / am not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he had / he would",
"he'd've": "he would have",
"he'll": "he shall / he will",
"he'll've": "he shall have / he will have",
"he's": "he has / he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how has / how is / how does",
"I'd": "I had / I would",
"I'd've": "I would have",
"I'll": "I shall / I will",
"I'll've": "I shall have / I will have",
"I'm": "I am",
"I've": "I have",
"I've'n't":"I have not",
"isn't": "is not",
"it'd": "it had / it would",
"it'd've": "it would have",
"it'll": "it shall / it will",
"it'll've": "it shall have / it will have",
"it's": "it has / it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she had / she would",
"she'd've": "she would have",
"she'll": "she shall / she will",
"she'll've": "she shall have / she will have",
"she's": "she has / she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so as / so is",
"that'd": "that would / that had",
"that'd've": "that would have",
"that's": "that has / that is",
"there'd": "there had / there would",
"there'd've": "there would have",
"there's": "there has / there is",
"they'd": "they had / they would",
"they'd've": "they would have",
"they'll": "they shall / they will",
"they'll've": "they shall have / they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
'u': 'you',
"u've": "you have",
"wasn't": "was not",
"we'd": "we had / we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what shall / what will",
"what'll've": "what shall have / what will have",
"what're": "what are",
"what's": "what has / what is",
"what've": "what have",
"when's": "when has / when is",
"when've": "when have",
"where'd": "where did",
"where's": "where has / where is",
"where've": "where have",
"who'll": "who shall / who will",
"who'll've": "who shall have / who will have",
"who's": "who has / who is",
"who've": "who have",
"why's": "why has / why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you had / you would",
"you'd've": "you would have",
"you'll": "you shall / you will",
"you'll've": "you shall have / you will have",
"you're": "you are",
"you've": "you have"
}
def cont(x):
  if (type(x) is str):
    for key in con:
      value=con[key]
      x=x.replace(key,value)
    return x
  else:
    return x

#headlines=cont(headlines)
#test_data=cont(test_data)

for i in range(0,len(data)):
  review= data[0][i]
  review= review.split()
  review= cont(review)
  review= " ".join(review)
  corpus.append(review)

for i in range(0,len(data2)):
  review= data2[0][i]
  review= review.split()
  review= cont(review)
  review= " ".join(review)
  corpus2.append(review)



In [17]:
corpus[0]

"a 'hindrance to operations': extracts from the leaked reports scorecard hughes' instant hit buoys blues jack gets his skates on at ice-cold alex chaos as maracana builds up for united depleted leicester prevail as elliott spoils everton's party hungry spurs sense rich pickings gunners so wide of an easy target derby raise a glass to strupar's debut double southgate strikes, leeds pay the penalty hammers hand robson a youthful lesson saints party like it's 1999 wear wolves have turned into lambs stump mike catches testy gough's taunt langer escapes to hit 167 flintoff injury piles on woe for england hunters threaten jospin with new battle of the somme kohl's successor drawn into scandal the difference between men and women sara denver, nurse turned solicitor diana's landmine crusade put tories in a panic yeltsin's resignation caught opposition flat-footed russian roulette sold out recovering a title"

In [18]:
data = pd.DataFrame(corpus)
data2 = pd.DataFrame(corpus2)

data.head()

0
0  a 'hindrance to operations': extracts from the...
1  scorecard the best lake scene leader: german s...
2  coventry caught on counter by flo united's riv...
3  pilgrim knows how to progress thatcher facing ...
4  hitches and horlocks beckham off but united su...

In [19]:
# removing punctuations, numbers, and special characters

data.replace("[^a-zA-Z]"," ",regex=True, inplace=True)


data2.replace("[^a-zA-Z]"," ",regex=True, inplace=True)

data.head()

0
0  a  hindrance to operations   extracts from the...
1  scorecard the best lake scene leader  german s...
2  coventry caught on counter by flo united s riv...
3  pilgrim knows how to progress thatcher facing ...
4  hitches and horlocks beckham off but united su...

In [20]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from textblob import Word
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [21]:
stops=stopwords.words("english")
unwanted=['no','nor','not']
stops=[ele for ele in stops if ele not in unwanted]
data[0] = data[0].apply(lambda x: " ".join(x for x in x.split() if x not in stops))
data2[0] = data2[0].apply(lambda x: " ".join(x for x in x.split() if x not in stops))

data.head()

0
0  hindrance operations extracts leaked reports s...
1  scorecard best lake scene leader german sleaze...
2  coventry caught counter flo united rivals road...
3  pilgrim knows progress thatcher facing ban mci...
4  hitches horlocks beckham united survive breast...

In [22]:
from nltk.stem import WordNetLemmatizer #to perform Lemmatizzation
from nltk.tokenize import word_tokenize
import nltk
nltk.download('omw-1.4')


lemmatize=WordNetLemmatizer()
data[0] = data[0].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
data2[0] = data2[0].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [23]:
data.head()

0
0  hindrance operation extract leaked report scor...
1  scorecard best lake scene leader german sleaze...
2  coventry caught counter flo united rival road ...
3  pilgrim know progress thatcher facing ban mcil...
4  hitch horlocks beckham united survive breast c...

In [24]:
data2.head()

0
0  case cancer result sheer bad luck rather unhea...
1  moscow gt beijing high speed train reduce trip...
2  u oil fall barrel toyota give away fuel cell p...
3  shot fired french magazine hq bibi netanyahus ...
4  new charlie hebdo issue come next week hard su...

In [25]:
headlines=data[0].tolist()
test_data= data2[0].tolist()

headlines[0]

'hindrance operation extract leaked report scorecard hughes instant hit buoy blue jack get skate ice cold alex chaos maracana build united depleted leicester prevail elliott spoil everton party hungry spur sense rich picking gunner wide easy target derby raise glass strupar debut double southgate strike leeds pay penalty hammer hand robson youthful lesson saint party like wear wolf turned lamb stump mike catch testy gough taunt langer escape hit flintoff injury pile woe england hunter threaten jospin new battle somme kohl successor drawn scandal difference men woman sara denver nurse turned solicitor diana landmine crusade put tory panic yeltsin resignation caught opposition flat footed russian roulette sold recovering title'

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
## implement BAG OF WORDS with 1-gram
countvector=CountVectorizer(ngram_range=(1,1))
traindataset=countvector.fit_transform(headlines)

In [28]:
# implement RandomForest Classifier
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(traindataset,train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [29]:
## Predict for the Test Dataset
test_transform= []
test_dataset = countvector.transform(test_data)
predictions = randomclassifier.predict(test_dataset)

In [30]:
## Import library to check accuracy
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [31]:
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[151  35]
 [ 17 175]]
0.8624338624338624
              precision    recall  f1-score   support

           0       0.90      0.81      0.85       186
           1       0.83      0.91      0.87       192

    accuracy                           0.86       378
   macro avg       0.87      0.86      0.86       378
weighted avg       0.87      0.86      0.86       378



In [32]:
countvector=CountVectorizer(ngram_range=(1,1))
traindataset=countvector.fit_transform(headlines)
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='gini')
randomclassifier.fit(traindataset,train['Label'])

RandomForestClassifier(n_estimators=200)

In [33]:
test_= []
test_da= countvector.transform(test_data)
predictions = randomclassifier.predict(test_da)

In [34]:
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[144  42]
 [ 14 178]]
0.8518518518518519
              precision    recall  f1-score   support

           0       0.91      0.77      0.84       186
           1       0.81      0.93      0.86       192

    accuracy                           0.85       378
   macro avg       0.86      0.85      0.85       378
weighted avg       0.86      0.85      0.85       378



In [35]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(traindataset.toarray(), train['Label'])

GaussianNB()

In [36]:
test_= []
test_da= countvector.transform(test_data)
predictions = gnb.predict(test_da.toarray())

In [37]:
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[156  30]
 [ 30 162]]
0.8412698412698413
              precision    recall  f1-score   support

           0       0.84      0.84      0.84       186
           1       0.84      0.84      0.84       192

    accuracy                           0.84       378
   macro avg       0.84      0.84      0.84       378
weighted avg       0.84      0.84      0.84       378



In [38]:
from sklearn import linear_model

logr = linear_model.LogisticRegression()
logr.fit(traindataset, train['Label'])

test_= []
test_= countvector.transform(test_data)
predictions = logr.predict(test_)

matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[149  37]
 [ 26 166]]
0.8333333333333334
              precision    recall  f1-score   support

           0       0.85      0.80      0.83       186
           1       0.82      0.86      0.84       192

    accuracy                           0.83       378
   macro avg       0.83      0.83      0.83       378
weighted avg       0.83      0.83      0.83       378



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [39]:
from sklearn.svm import SVC  

clf = SVC(kernel='linear') 
  
# fitting x samples and y classes 
clf.fit(traindataset, train['Label']) 

test_= []
test_= countvector.transform(test_data)
predictions = clf.predict(test_)

matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[149  37]
 [ 28 164]]
0.828042328042328
              precision    recall  f1-score   support

           0       0.84      0.80      0.82       186
           1       0.82      0.85      0.83       192

    accuracy                           0.83       378
   macro avg       0.83      0.83      0.83       378
weighted avg       0.83      0.83      0.83       378



In [40]:
'''
from sklearn.model_selection import GridSearchCV
 
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf', 'linear']}
 
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
 
# fitting the model for grid search
grid.fit(traindataset, train['Label'])'''

"\nfrom sklearn.model_selection import GridSearchCV\n \n# defining parameter range\nparam_grid = {'C': [0.1, 1, 10, 100, 1000],\n              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],\n              'kernel': ['rbf', 'linear']}\n \ngrid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)\n \n# fitting the model for grid search\ngrid.fit(traindataset, train['Label'])"

In [41]:
'''# print best parameter after tuning
print(grid.best_params_)
 
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)'''

'# print best parameter after tuning\nprint(grid.best_params_)\n \n# print how our model looks after hyper-parameter tuning\nprint(grid.best_estimator_)'

In [42]:
''' from sklearn.svm import SVC  

clf = SVC(C=0.1, gamma=1) 
  
# fitting x samples and y classes 
clf.fit(traindataset, train['Label']) 

test_= []
test_= countvector.transform(test_data)
predictions = clf.predict(test_)

matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)'''

" from sklearn.svm import SVC  \n\nclf = SVC(C=0.1, gamma=1) \n  \n# fitting x samples and y classes \nclf.fit(traindataset, train['Label']) \n\ntest_= []\ntest_= countvector.transform(test_data)\npredictions = clf.predict(test_)\n\nmatrix=confusion_matrix(test['Label'],predictions)\nprint(matrix)\nscore=accuracy_score(test['Label'],predictions)\nprint(score)\nreport=classification_report(test['Label'],predictions)\nprint(report)"

In [43]:
## implement BAG OF WORDS with 2-grams
countvector=CountVectorizer(ngram_range=(2,2))
bg_2gram=countvector.fit_transform(headlines)

In [44]:
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(bg_2gram,train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [45]:
test_= []
test_= countvector.transform(test_data)
predictions = randomclassifier.predict(test_)

In [46]:
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[132  54]
 [  0 192]]
0.8571428571428571
              precision    recall  f1-score   support

           0       1.00      0.71      0.83       186
           1       0.78      1.00      0.88       192

    accuracy                           0.86       378
   macro avg       0.89      0.85      0.85       378
weighted avg       0.89      0.86      0.85       378



In [47]:
randomclassifier=RandomForestClassifier(n_estimators=200)
randomclassifier.fit(bg_2gram,train['Label'])

test_= []
test_= countvector.transform(test_data)
predictions = randomclassifier.predict(test_)

matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[130  56]
 [  0 192]]
0.8518518518518519
              precision    recall  f1-score   support

           0       1.00      0.70      0.82       186
           1       0.77      1.00      0.87       192

    accuracy                           0.85       378
   macro avg       0.89      0.85      0.85       378
weighted avg       0.89      0.85      0.85       378



In [48]:
import xgboost as xgb

In [49]:
xgb_classifier = xgb.XGBClassifier()
xgb_classifier.fit(bg_2gram,train['Label'])

XGBClassifier()

In [50]:
test_= []
test_= countvector.transform(test_data)
predictions = xgb_classifier.predict(test_)

matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[ 74 112]
 [ 13 179]]
0.6693121693121693
              precision    recall  f1-score   support

           0       0.85      0.40      0.54       186
           1       0.62      0.93      0.74       192

    accuracy                           0.67       378
   macro avg       0.73      0.67      0.64       378
weighted avg       0.73      0.67      0.64       378



In [52]:
'''import numpy as np
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt','log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10,14]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4,6,8]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(random_grid)'''

"import numpy as np\nfrom sklearn.model_selection import RandomizedSearchCV\n# Number of trees in random forest\nn_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]\n# Number of features to consider at every split\nmax_features = ['auto', 'sqrt','log2']\n# Maximum number of levels in tree\nmax_depth = [int(x) for x in np.linspace(10, 1000,10)]\n# Minimum number of samples required to split a node\nmin_samples_split = [2, 5, 10,14]\n# Minimum number of samples required at each leaf node\nmin_samples_leaf = [1, 2, 4,6,8]\n# Create the random grid\nrandom_grid = {'n_estimators': n_estimators,\n               'max_features': max_features,\n               'max_depth': max_depth,\n               'min_samples_split': min_samples_split,\n               'min_samples_leaf': min_samples_leaf,\n              'criterion':['entropy','gini']}\nprint(random_grid)"

In [53]:
'''rf=RandomForestClassifier()
rf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
rf_randomcv.fit(traindataset,train['Label'])'''

"rf=RandomForestClassifier()\nrf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,\n                               random_state=100,n_jobs=-1)\nrf_randomcv.fit(traindataset,train['Label'])"

In [54]:
'''rf_randomcv.best_params_'''

'rf_randomcv.best_params_'

In [55]:
countvector=CountVectorizer(ngram_range=(3,3))
traindataset=countvector.fit_transform(headlines)
randomclassifier=RandomForestClassifier(n_estimators=100,criterion='gini')
randomclassifier.fit(traindataset,train['Label'])

RandomForestClassifier()

In [56]:
test_= []
test_= countvector.transform(test_data)
predictions = randomclassifier.predict(test_)

matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[130  56]
 [  0 192]]
0.8518518518518519
              precision    recall  f1-score   support

           0       1.00      0.70      0.82       186
           1       0.77      1.00      0.87       192

    accuracy                           0.85       378
   macro avg       0.89      0.85      0.85       378
weighted avg       0.89      0.85      0.85       378



In [57]:
randomclassifier=RandomForestClassifier(criterion='entropy')
randomclassifier.fit(traindataset,train['Label'])

test_= []
test_= countvector.transform(test_data)
predictions = randomclassifier.predict(test_)

matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[130  56]
 [  0 192]]
0.8518518518518519
              precision    recall  f1-score   support

           0       1.00      0.70      0.82       186
           1       0.77      1.00      0.87       192

    accuracy                           0.85       378
   macro avg       0.89      0.85      0.85       378
weighted avg       0.89      0.85      0.85       378



In [61]:
xgb_classifier = xgb.XGBClassifier()
xgb_classifier.fit(traindataset,train['Label'])

test_= []
test_= countvector.transform(test_data)
predictions = xgb_classifier.predict(test_)

matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[ 40 146]
 [  9 183]]
0.58994708994709
              precision    recall  f1-score   support

           0       0.82      0.22      0.34       186
           1       0.56      0.95      0.70       192

    accuracy                           0.59       378
   macro avg       0.69      0.58      0.52       378
weighted avg       0.68      0.59      0.52       378



In [59]:
train['Label'].value_counts()

1    2096
0    1879
Name: Label, dtype: int64